project:
  type: website
  output-dir: docs
  
website:
  title: "Rafael Sant'Ana Herzog"
  navbar:
    left:
      - href: index.qmd
        text: Sobre mim
      - posts.qmd


format:
  html:
    theme: styles.scss
    mainfont: Gabarito
    css: styles.css
    toc: true
    page-layout: full

editor: source

